apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhc-arm64
  namespace: puc-rio
  labels:
    app: dhc-arm64
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dhc-arm64
  template:
    metadata:
      labels:
        app: dhc-arm64
    spec:
      nodeSelector: 
        kubernetes.io/arch: arm64
      containers:
      - name: web
        image: arthurcgc/dhc:arm64
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            port: 8888
            path: /healthcheck
        readinessProbe:
          httpGet:
            port: 8888
            path: /healthcheck
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "64Mi"
            cpu: "250m"
            

