apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhc-arm64
  namespace: puc-rio
  labels:
    app: dhc-arm64
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dhc-arm64
  template:
    metadata:
      labels:
        app: dhc-arm64
    spec:
      nodeSelector: 
        kubernetes.io/arch: arm64
      containers:
      - name: web
        imagePullPolicy: Always
        image: arthurcgc/dhc:arm64
        ports:
        - containerPort: 8888
