apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhc
  namespace: puc-rio
  labels:
    app: dhc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dhc
  template:
    metadata:
      labels:
        app: dhc
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: web
        image: arthurcgc/dhc:amd64
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
